periodics:
# gce
- interval: 5m
  name: ci-kubernetes-e2e-gci-gce-scalability
  tags:
  - "perfDashPrefix: gce-100Nodes"
  - "perfDashJobType: performance"
  - "perfDashBuildsCount: 1"
  labels:
    preset-service-account: "false"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/scp-engsrvperfdev-gcp/test-sh:2.0
      command: ["./run-e2e.sh"]
      args: ["cluster-loader"]
